In [9]:
import pandas as pd
import numpy as np

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
from keras.layers import RepeatVector
from keras.layers import TimeDistributed


tfhub_handle_preprocess = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
tfhub_handle_encoder = 'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1'


def bert_preprocessing(X):
    bert_preprocess_model = hub.KerasLayer(tfhub_handle_preprocess)
    X_pre = bert_preprocess_model(X)
    return X_pre



In [2]:
df_fin = pd.read_csv('../raw_data/yelp_heading_split/data_yelp_heading_split_yelp_Financial_Services')

review   recommendation
0      Drive up ATM is difficult to navigate to in a ...  Not Recommended
1      When I need retail therapy, Mink is where I go...      Recommended
2      This place for the most part is awful.  Chase ...  Not Recommended
3      Working with Jesse made shopping for health in...      Recommended
4      Ive put over 60,000 miles on my Subaru Legacy ...      Recommended
...                                                  ...              ...
28535  A double dip if you play the game-2-15-19 I pu...  Not Recommended
28536  I had ALD for many year and they were helpfull...  Not Recommended
28537  I've used Safe Responsible Movers twice now, a...      Recommended
28538  I'm so greatly appreciative to David Bartolme....      Recommended
28539  I went in to open a new checking account becau...  Not Recommended

[28540 rows x 2 columns]

In [10]:
X = df_fin.review

X_pre = bert_preprocessing(X)

In [13]:
X_pre

{'input_mask': <tf.Tensor: shape=(28540, 128), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>,
 'input_word_ids': <tf.Tensor: shape=(28540, 128), dtype=int32, numpy=
 array([[ 101, 3298, 2039, ...,    0,    0,    0],
        [ 101, 2043, 1045, ...,    0,    0,    0],
        [ 101, 2023, 2173, ...,    0,    0,    0],
        ...,
        [ 101, 1045, 1005, ..., 1010, 2673,  102],
        [ 101, 1045, 1005, ..., 1012, 2029,  102],
        [ 101, 1045, 2253, ..., 1998, 2070,  102]], dtype=int32)>,
 'input_type_ids': <tf.Tensor: shape=(28540, 128), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>}